# Generated by Django 3.0.8 on 2021-06-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenesUnicauca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamenesUnicauca.Contribution')),
                ('topic', models.CharField(max_length=2048)),
            ],
            bases=('ExamenesUnicauca.contribution',),
        ),
    ]
