# Generated by Django 3.0.8 on 2021-06-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenesUnicauca', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
