# Generated by Django 3.0.8 on 2021-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenesUnicauca', '0003_contribution_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
